In [31]:
import cv2
import numpy as np
import utils
from numpy import matrix as mat
np.set_printoptions(formatter={'all':lambda x: '{:8.3f}'.format(x)})

In [32]:
def generate_3d_points():
    ax=np.linspace(-100,100,3)
    xx,yy=np.meshgrid(ax,ax)
    return np.vstack((xx.flatten(),yy.flatten(),np.zeros(len(ax)**2))).T
generate_3d_points()

array([[-100.000, -100.000,    0.000],
       [   0.000, -100.000,    0.000],
       [ 100.000, -100.000,    0.000],
       [-100.000,    0.000,    0.000],
       [   0.000,    0.000,    0.000],
       [ 100.000,    0.000,    0.000],
       [-100.000,  100.000,    0.000],
       [   0.000,  100.000,    0.000],
       [ 100.000,  100.000,    0.000]])

In [40]:
K=mat([160.0,0,160, 0,160.0,120.0,0,0,1]).reshape(3,3)
x,y,z=0,0,500.0
rx,ry,rz=-90/180.0*np.pi,0,0
rx=0
ry=0
rz=0#-90/180.0*np.pi
T=np.array([x,y,z])
R=utils.eulerAnglesToRotationMatrix([rx,ry,rz]) 
pts=(K*((mat(R)*generate_3d_points().T).T+T).T).T
print(pts/pts[:,2])
#(mat(R)*generate_3d_points().T).T

[[ 128.000   88.000    1.000]
 [ 160.000   88.000    1.000]
 [ 192.000   88.000    1.000]
 [ 128.000  120.000    1.000]
 [ 160.000  120.000    1.000]
 [ 192.000  120.000    1.000]
 [ 128.000  152.000    1.000]
 [ 160.000  152.000    1.000]
 [ 192.000  152.000    1.000]]
